name: "xuwang50309's Action in Action"
description: 'Greets someone and returns always 42.'
inputs:
  who-to-greet: 'myname'
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  answer: 'myanswer'
    description: 'The answer to everythig (always 42)'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    
